name: build and publish

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

env:
  TERM: xterm-256color
  REPO_NAME: 9jkh/certbot-dns

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: build docker image
        run: make build

      - name: test docker image
        run: make test

      - name: publish docker image
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: make publish
